name: Floric
options:
  bundleIdPrefix: co.sultans.floric
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "-"
    SWIFT_TREAT_WARNINGS_AS_ERRORS: NO
    GCC_TREAT_WARNINGS_AS_ERRORS: NO
targets:
  Floric:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Floric
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: co.sultans.floric
        PRODUCT_NAME: Floric
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_CFBundleDisplayName: Floric
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
